
```{r, include = FALSE}
library(tidyverse)
library(janitor)
library(dplyr)
library(reshape2)

```

### Data Reading and Viewing
```{r}
csv <- "analyticdata2024 - clean_data.csv"

mental <- read.csv(csv, header = TRUE)

### Clean data columns
mental %>% clean_names()

### Overview of data as a whole
mental %>% glimpse()
```

### Filtering in relavent correlations between FEATURES Themselves and using a cutoff
```{r}
mental_filtered <- mental %>% select(where(is.numeric))

correlations <- cor(mental_filtered) 

correlations <- melt(correlations, na.rm = TRUE)

cor_feature <- correlations %>% distinct(value, .keep_all = TRUE) %>% filter( (value > 0.70 & value < 1) | value < -0.70)

```

### View Table of relavent correlations between FEATURES:
```{r, include=FALSE}
cor_feature
```

### Filtering in relavent correlations between RESPONSE and Features Themselves and using a cutoff
```{r}

cor_response <- correlations %>% distinct(value, .keep_all = TRUE) %>% filter(Var2 == "Poor.Mental.Health.Days.raw.value")

```

### View Table of relavent correlations between RESPONSE and Feature:
```{r, include=FALSE}
cor_response
```

